@startuml
'https://plantuml.com/sequence-diagram

class Forum{
-topic: string <<final>>
+add(child: Theme): void
+remove(index: integer): void
+size(): integer
+toString():String
}
class Theme{
-topic: string <<final>>
+this(topic:string): Theme
+sujet(): string
+add((child: Salon):void
+remove((index: integer): void
+size(): integer
+toString(): string
}

class Salon{
-topic: string <<final>>
+this((topic:string):Salon
+sujet():string
+add((child: Message):void
+remove((index: integer): void
+size(): integer
+toString(): string
}

class Message{
-topic: string <<final>>
-contenu: string <<final>>
+this(topic:string, contenu: string): Message
+sujet():string
+toString():string
}
@enduml