/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public final class App {

    private App(){}

    public static void main(String[] args) {
        Ampoule a = new Ampoule(); // on est initialement en AmpouleEteinte
        a.eteindre(); // "déjà éteinte"
        a.allumer();  // "-> allumée" + on passe en AmpouleAllumee
        a.allumer();  // "déjà allumée"
        a.eteindre(); // etc
        a.allumer(); // etc
        a.eteindre(); // etc
        a.allumer(); // "-> cassée" + on passe en AmpouleCassée
    }
}
